/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/untitled.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[0, -0.01, 0]}>
                        <group name="Tube001" position={[0.06, 0.21, -0.07]} scale={[0.21, 0.21, 0.21]}>
                            <group position={[0, 0, -9.07]}>
                                <mesh
                                    geometry={nodes['Tube001_15_-_Default_0'].geometry}
                                    material={nodes['Tube001_15_-_Default_0'].material}
                                />
                            </group>
                        </group>
                        <group position={[8.21, -12.33, 10.24]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={nodes['Object001_15_-_Default_0'].geometry}
                                material={nodes['Object001_15_-_Default_0'].material}
                            />
                        </group>
                        <group position={[8.21, -12.33, 10.24]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={nodes['Object002_15_-_Default_0'].geometry}
                                material={nodes['Object002_15_-_Default_0'].material}
                            />
                        </group>
                        <group position={[8.21, -12.33, 10.24]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={nodes['Sphere050_15_-_Default_0'].geometry}
                                material={nodes['Sphere050_15_-_Default_0'].material}
                            />
                        </group>
                        <group position={[-16.27, 7.56, 7.18]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={nodes['Tube002_15_-_Default_0'].geometry}
                                material={nodes['Tube002_15_-_Default_0'].material}
                            />
                        </group>
                        <group position={[12.79, 12.47, -14.25]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh
                                geometry={nodes['Tube003_15_-_Default_0'].geometry}
                                material={nodes['Tube003_15_-_Default_0'].material}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/untitled.glb')
